# Generated by Django 5.2.10 on 2026-01-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('full-time', 'Full-time'), ('part-time', 'Part-time')], default='remote', max_length=20),
        ),
    ]
