# Generated by Django 5.2.10 on 2026-01-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobapplication_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('office', 'Office'), ('hybrid', 'Hybrid'), ('part-time', 'Part-time')], default='remote', max_length=20),
        ),
    ]
